meta_product_name: "Zygomatic"
meta_title: "Zygomatic - one laugh a day keeps the doctor away"
meta_description: "Relevant description"
meta_image: "logo.png"                       # should exist in `app/assets/images/`
twitter_account: "@zygomatic"   # required for Twitter Cards
